---
output: html_document
author:
- name: Marco Sciaini
  affiliation: University of Goettingen
- name: Sangeeta Bhatia
  affiliation: Imperial College London
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
---

```{r setup, eval = TRUE}

library(dplyr)
library(magrittr)
library(ggplot2)
library(PopGenReport)
library(secr)
```
## Read in parameter values

```{r}
# source packages, function and parameters
source("../R/packages.R")
source("../R/functions_landscape.R")
source("../R/functions_population.R")
source("../R/globals.R")
```

## Landscape Simulation

```{r ls_params}
# simulate initial landscape ----
landscape <- simulate_landscape_discrete(para$n_col,
                                         para$n_row,
                                         germs = 100)
```


## Population Initialization

```{r}
pops <- create_pops(para$n_pops, 
                    2,
                    landscape)

# initialize the populations ----
pop_new <- init_pops(n_pops    =  para$n_pops,
                     n_ind     =  para$n_ind,
                     sex_ratio =  para$sex_ratio,
                     n_allels  =  para$n_allels,
                     n_loci    =  para$n_loci,
                     n_cov     =  para$n_cov,
                     pops      =  pops)

```

## Simulation

For each value of resistance, update the landscape, simulate
population and calculate summary statistics. Do this multiple times. 


```{r}
plan(multisession)  
y <- future_lapply(para$resistance,
                   FUN =  simulate_abc,
                   rep_resistance = para$rep_resistance)
```

